# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-executables-have-shebangs
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: clang-format-14
        language: system
        files: \.(cpp|hpp)$
        args: ['-fallback-style=none', '-i']

  - repo: local
    hooks:
      - id: install-source-dependencies
        name: install-source-dependencies
        description: Install source dependencies to build folder if missing
        entry: conan install . -of .  --build=missing
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: generate-compilation-database
        name: generate compilation database
        description: Generate compile_commands.json
        entry: generate_compile_commands.bash
        pass_filenames: false
        language: script

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: run_clang_tidy.bash
        files: \.(cpp|hpp)$
        language: script
